#!/usr/bin/env ruby
require File.expand_path('boot.rb', File.dirname(__FILE__))

class ServerCommand < Thor
  desc "start", "start the server"
  options port:     15000
  options listen:   "0.0.0.0"
  options demonize: false
  options env:      "development"
  options ui:       false
  def start
    throw "demonize unsupported for now time" if options[:demonize]
    EventMachine.synchrony do
      Server.new(options).start
    end
  end
  
  desc "config", "Create basic config files"
  def config
    DConfig.write_example("./config/database.yml")
  end
end

ServerCommand.start