#!/usr/bin/env ruby
require File.expand_path('boot.rb', File.dirname(__FILE__))

class ServerCommand < Thor
  desc "start", "start the server"
  options port:     15000
  options listen:   "0.0.0.0"
  options demonize: false
  options env:      "development"
  def start
    throw "demonize unsupported for now time" if options[:demonize]
    EventMachine::run do
      $server = Server.new(options)
      $server.enterDebugMode if Server.env != "production"
      $server.start
    end
  end
end

ServerCommand.start